#!/bin/bash

NUM_PLAYERS=$((TEAMMATES_LEN + 1))
CUSTOM_AGENT_CK_RATE_GENERATION=$((NUM_PLAYERS + 1))
NUM_STEPS_IN_TRAJ_FOR_DYN_ADV=2
NUM_STATIC_ADVS_PER_HEATMAP=1
NUM_DYNAMIC_ADVS_PER_HEATMAP=1
USE_VAL_FUNC_FOR_HEATMAP_GEN=true
PRIORITIZED_SAMPLING=false

if [ -z ${EXP_NAME_PREFIX} ]; then
    EXP_NAME_PREFIX=""
fi

if [ "$QUICK_TEST" = false ]; then
  WANDB_MODE="online"
  N_ENVS=210
  EPOCH_TIMESTEPS=100000
  POP_TOTAL_TRAINING_TIMESTEPS=$(echo "$HOW_LONG * 5000000" | bc)
  N_X_SP_TOTAL_TRAINING_TIMESTEPS=$(echo "$HOW_LONG * 5000000" | bc)
  FCP_TOTAL_TRAINING_TIMESTEPS=$(echo "$HOW_LONG * 5000000" | bc)
  ADVERSARY_TOTAL_TRAINING_TIMESTEPS=$(echo "$HOW_LONG * 5000000" | bc)
  N_X_FCP_TOTAL_TRAINING_TIMESTEPS=$(echo "2 * $FCP_TOTAL_TRAINING_TIMESTEPS * $HOW_LONG" | bc)
else
  WANDB_MODE="disabled"
  N_ENVS=2
  EPOCH_TIMESTEPS=2
  POP_TOTAL_TRAINING_TIMESTEPS=4000
  N_X_SP_TOTAL_TRAINING_TIMESTEPS=4000
  ADVERSARY_TOTAL_TRAINING_TIMESTEPS=1500
  FCP_TOTAL_TRAINING_TIMESTEPS=1500
  N_X_FCP_TOTAL_TRAINING_TIMESTEPS=3000
  EXP_DIR="Test/$EXP_DIR"
fi