name: mHRI
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - liblsl
  - pugixml
  - pip
  - pip:
      - stable-baselines3==2.7.1
      - gymnasium==1.1.1
      - wandb==0.25.0
      - pygame==2.6.1
      - pydantic==2.12.5
      - torch==2.8.0
